//LOGGIN RESOURCE
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

//AUTH RESOURCE
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'

//LOGOUT RESOURCE
export const LOGOUT_FETCHING = 'LOGOUT_FETCHING'
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED'
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED'