//GET resource list
export const GET_RESOURCE_FETCHING = 'GET_RESOURCE_FETCHING'
export const GET_RESOURCE_FULFILLED = 'GET_RESOURCE_FULFILLED'
export const GET_RESOURCE_REJECTED = 'GET_RESOURCE_REJECTED'

//ADD resource 
export const ADD_RESOURCE_FETCHING = 'ADD_RESOURCE_FETCHING'
export const ADD_RESOURCE_FULFILLED = 'ADD_RESOURCE_FULFILLED'
export const ADD_RESOURCE_REJECTED = 'ADD_RESOURCE_REJECTED'

//UPDATE resource 
export const UPDATE_RESOURCE_FETCHING = 'UPDATE_RESOURCE_FETCHING'
export const UPDATE_RESOURCE_FULFILLED = 'UPDATE_RESOURCE_FULFILLED'
export const UPDATE_RESOURCE_REJECTED = 'UPDATE_RESOURCE_REJECTED'

//DELETE resource 
export const DELETE_RESOURCE_FETCHING = 'DELETE_RESOURCE_FETCHING'
export const DELETE_RESOURCE_FULFILLED = 'DELETE_RESOURCE_FULFILLED'
export const DELETE_RESOURCE_REJECTED = 'DELETE_RESOURCE_REJECTED'