export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const modalTypes = {
  ADD_RESOURCE: 'ADD_RESOURCE',
  EDIT_RESOURCE: 'EDIT_RESOURCE',
  DELETE_RESOURCE: 'DELETE_RESOURCE'
}
